### ISSUE TITLE
[LaunchSuite] Error while downloading: {code: "ECONNRESET"}

### ISSUE THREAD

**Issue by AutumnVN** [moehreag/AxolotlClient#3]
**Describe the bug**
At title

**To Reproduce**
1. Click on 'play'
2. Go to Console
3. See error

**Expected behavior**
Expect it run

**Screenshots**
![image](https://user-images.githubusercontent.com/77253698/147068597-f57e022d-4ecb-417e-afa8-f65ab4289120.png)

**Envroiment (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by moehreag** [comment]
First of all, thanks for opening an issue and showing interest in this project. Further your issue probably relates to the stability of your internet connection (If you think it's stable, it should be and the issue is caused by a specific file hosting site (In my cases GitHub, modrinth or CurseForge) which had an outage at the time.)

**Comment by AutumnVN** [comment]
Thank you, i fixed it by try re-download multiple times (don't know why it decided to throw error in middle download, my internet is ok, i can play online game), then one fabric lib files broken (maybe because i re-download when get error many times) so i manually download that file to replace.
